### ISSUE TITLE
Update OpenAIWrapper to add fine tuning functionality with unit test cases.

### ISSUE THREAD

**Issue by Barqawiz** [intelligentnode/IntelliNode#15]
**Openai Reference**:
- check Fine-tuning steps in : https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates.
- full guide: https://platform.openai.com/docs/guides/fine-tuning/create-a-fine-tuned-model

**Work scope**:
The Openai API supports the ability to upload a json file with the training data and run fine-tuning functions on the data. Supporting this in intelliNode requires adding the following minimum functions to [OpenAIWrapper.js](https://github.com/Barqawiz/IntelliNode/blob/main/IntelliNode/wrappers/OpenAIWrapper.js): 
- upload fine tuning file.
- create fine tune job.
- use fine tune model.

**Step1**: Prepare the testing data in a file, for example:
```
{
  "messages": [
    { "role": "system", "content": "You are an assistant that occasionally misspells words" },
    { "role": "user", "content": "Tell me a story." },
    { "role": "assistant", "content": "One day a student went to schoool." }
  ]
}
```

**Step2**: Add a function inside OpenAIWrapper that match the following call to upload the file:
```
curl https://api.openai.com/v1/files \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -F "purpose=fine-tune" \
  -F "file=@path_to_your_file" 
```
**Step3**: Add a function inside OpenAIWrapper that match the following call to create fine tuning hob:
```
curl https://api.openai.com/v1/fine_tuning/jobs \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
  "training_file": "TRAINING_FILE_ID",
  "model": "gpt-3.5-turbo-0613"
}'
```

**Testing**:
Add the testing scripts in [OpenAIWrapper.test.js](https://github.com/Barqawiz/IntelliNode/blob/main/IntelliNode/test/integration/OpenAIWrapper.test.js):
- Test calling upload file.
- Test calling create fine tune job.
- Test calling the existing chat function with the fine tuned model name.

**Comment by Thedevelop3r** [comment]
added fine tuning functionality, with unit tests

https://github.com/intelligentnode/IntelliNode/pull/48
